name: Update README and LICENSE

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # Every day at 4 AM UTC

jobs:
  update-readme-license:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Checkout source README template
        uses: actions/checkout@v4
        with:
          repository: ivancarlosti/.github
          ref: main
          path: source_readme

      - name: Update README.md (buttons and footer)
        run: |
          set -e
          REPO_NAME="${GITHUB_REPOSITORY##*/}"

          BUTTONS=$(awk '/<!-- buttons -->/{flag=1;next}/<!-- endbuttons -->/{flag=0}flag' source_readme/README.md)
          BUTTONS_UPDATED=$(echo "$BUTTONS" | sed "s/\.github/${REPO_NAME}/g")

          FOOTER=$(awk '/<!-- footer -->/{flag=1}flag' source_readme/README.md)

          UPDATED=$(awk -v buttons="$BUTTONS_UPDATED" '
            BEGIN { skip=0 }
            /<!-- buttons -->/ {
              print
              print buttons
              skip=1
              next
            }
            /<!-- endbuttons -->/ && skip {
              print
              skip=0
              next
            }
            !skip { print }
          ' README.md)

          echo "$UPDATED" | awk -v footer="$FOOTER" '
            /<!-- footer -->/ {
              print footer
              found=1
              exit
            }
            { print }
          ' > README.tmp && mv README.tmp README.md

      - name: Download LICENSE directly from raw URL
        run: |
          curl -sSL https://raw.githubusercontent.com/ivancarlosti/.github/main/LICENSE -o LICENSE

      - name: Stage updated files
        run: git add README.md LICENSE

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: |
            README.md
            LICENSE
          commit_message: "Sync README and LICENSE from template [▶️]"
          branch: ${{ github.ref_name }}
